#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/update-changelog.sh
  scripts/update-changelog.sh --version VERSION [--date YYYY-MM-DD]

Without --version, updates the Unreleased section from commits since the latest
git tag. With --version, creates or replaces that version section using the same
commit range and resets Unreleased to "No notable changes."
USAGE
}

version=""
release_date="$(date +%F)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      version="${2:-}"
      shift 2
      ;;
    --date)
      release_date="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -n "$version" && ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-+][0-9A-Za-z.-]+)?$ ]]; then
  echo "Version must be semantic versioning, such as 0.1.0 or 1.2.3-beta.1." >&2
  exit 1
fi

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

latest_tag="$(git tag --list --sort=-v:refname | head -n 1 || true)"
if [[ -n "$latest_tag" ]]; then
  commit_range="${latest_tag}..HEAD"
else
  commit_range="HEAD"
fi

tmp_entries="$(mktemp)"
tmp_released="$(mktemp)"
tmp_groups="$(mktemp -d)"
trap 'rm -f "$tmp_entries" "$tmp_released"; rm -rf "$tmp_groups"' EXIT

git log --no-merges --pretty=format:%s "$commit_range" > "$tmp_entries"

added_file="$tmp_groups/added"
fixed_file="$tmp_groups/fixed"
security_file="$tmp_groups/security"
docs_file="$tmp_groups/docs"
tests_file="$tmp_groups/tests"
ci_file="$tmp_groups/ci"
changed_file="$tmp_groups/changed"
touch "$added_file" "$fixed_file" "$security_file" "$docs_file" "$tests_file" "$ci_file" "$changed_file"

while IFS= read -r subject; do
  [[ -z "$subject" ]] && continue

  if [[ "$subject" =~ ^(feat|feature|add)(\(.+\))?: ]] || [[ "$subject" =~ ^[Aa]dd(ed)?[[:space:]] ]]; then
    printf '%s\n' "$subject" >> "$added_file"
  elif [[ "$subject" =~ ^(fix|bugfix)(\(.+\))?: ]] || [[ "$subject" =~ ^[Ff]ix(ed)?[[:space:]] ]]; then
    printf '%s\n' "$subject" >> "$fixed_file"
  elif [[ "$subject" =~ ^security(\(.+\))?: ]] || [[ "$subject" =~ [Aa]uth|[Aa]uthorization|[Aa]uthentication|[Ss]andbox|[Ee]ncrypt|[Ss]ecret|[Cc]redential ]]; then
    printf '%s\n' "$subject" >> "$security_file"
  elif [[ "$subject" =~ ^docs?(\(.+\))?: ]] || [[ "$subject" =~ README|readme|[Cc]hangelog|[Ll]icense ]]; then
    printf '%s\n' "$subject" >> "$docs_file"
  elif [[ "$subject" =~ ^tests?(\(.+\))?: ]] || [[ "$subject" =~ [Tt]est ]]; then
    printf '%s\n' "$subject" >> "$tests_file"
  elif [[ "$subject" =~ ^(ci|build)(\(.+\))?: ]] || [[ "$subject" =~ [Ww]orkflow|Docker|docker|[Cc]ontainer|[Pp]ublish|[Pp]ackage ]]; then
    printf '%s\n' "$subject" >> "$ci_file"
  else
    printf '%s\n' "$subject" >> "$changed_file"
  fi
done < "$tmp_entries"

write_group() {
  local title="$1"
  local file="$2"

  if [[ ! -s "$file" ]]; then
    return
  fi

  printf '### %s\n\n' "$title"
  while IFS= read -r subject; do
    [[ -z "$subject" ]] && continue
    printf -- '- %s\n' "$subject"
  done < "$file"
  printf '\n'
}

write_changes() {
  if [[ ! -s "$tmp_entries" ]]; then
    printf 'No notable changes.\n\n'
    return
  fi

  write_group "Added" "$added_file"
  write_group "Fixed" "$fixed_file"
  write_group "Security" "$security_file"
  write_group "Documentation" "$docs_file"
  write_group "Tests" "$tests_file"
  write_group "CI/CD" "$ci_file"
  write_group "Changed" "$changed_file"
}

extract_released_sections() {
  local excluded_version="$1"

  if [[ ! -f CHANGELOG.md ]]; then
    return
  fi

  awk -v excluded="## ["$excluded_version"]" '
    /^## \[/ {
      keep = ($0 !~ /^## \[Unreleased\]/ && (excluded == "## []" || index($0, excluded) != 1))
    }
    keep { print }
  ' CHANGELOG.md
}

extract_released_sections "$version" > "$tmp_released"

{
  cat <<'HEADER'
# Changelog

All notable changes to SporeSync will be documented in this file.

The format is based on Keep a Changelog, and this project uses semantic
versioning for release tags. This file is generated by `scripts/update-changelog.sh`.

## [Unreleased]

HEADER

  if [[ -n "$version" ]]; then
    printf 'No notable changes.\n\n'
    printf '## [%s] - %s\n\n' "$version" "$release_date"
    write_changes
  else
    write_changes
  fi

  if [[ -s "$tmp_released" ]]; then
    cat "$tmp_released"
  fi
} > CHANGELOG.md
